# Generated by Django 6.0.2 on 2026-02-19 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ACCESS_EHR', 'Access EHR Record'), ('ACCESS_REPORT', 'Access Medical Report'), ('ACCESS_LAB', 'Access Lab Result'), ('EMERGENCY_TOKEN_ISSUED', 'Emergency Token Issued'), ('EMERGENCY_TOKEN_USED', 'Emergency Token Used'), ('EMERGENCY_TOKEN_EXPIRED', 'Emergency Token Expired'), ('LOGIN', 'User Login'), ('LOGOUT', 'User Logout')], max_length=50)),
                ('resource_type', models.CharField(blank=True, max_length=50, null=True)),
                ('resource_id', models.CharField(blank=True, max_length=50, null=True)),
                ('access_granted', models.BooleanField(default=False)),
                ('is_emergency', models.BooleanField(default=False)),
                ('details', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
