# Generated by Django 6.0.2 on 2026-02-19 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5)),
                ('contact_number', models.CharField(max_length=15)),
                ('emergency_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('xray', 'X-Ray'), ('mri', 'MRI'), ('blood_test', 'Blood Test'), ('urine_test', 'Urine Test'), ('ecg', 'ECG'), ('ct_scan', 'CT Scan'), ('biopsy', 'Biopsy'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('findings', models.TextField(blank=True, null=True)),
                ('sensitivity_level', models.IntegerField(default=1)),
                ('required_clearance_level', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reports', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_reports', to='ehr.patient')),
            ],
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=200)),
                ('test_date', models.DateField()),
                ('result_value', models.CharField(max_length=200)),
                ('normal_range', models.CharField(blank=True, max_length=100, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('is_abnormal', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('sensitivity_level', models.IntegerField(default=1)),
                ('required_clearance_level', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lab_results', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to='ehr.patient')),
            ],
        ),
        migrations.CreateModel(
            name='EHRRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('general', 'General Health'), ('mental_health', 'Mental Health'), ('genetic', 'Genetic Information'), ('substance', 'Substance Abuse'), ('chronic', 'Chronic Condition'), ('surgical', 'Surgical History'), ('emergency', 'Emergency Record')], default='general', max_length=20)),
                ('sensitivity_level', models.IntegerField(choices=[(1, 'Level 1 - General'), (2, 'Level 2 - Standard'), (3, 'Level 3 - Sensitive'), (4, 'Level 4 - Highly Sensitive'), (5, 'Level 5 - Critical')], default=1)),
                ('diagnosis', models.TextField()),
                ('treatment_plan', models.TextField(blank=True, null=True)),
                ('medications', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('required_clearance_level', models.IntegerField(default=1)),
                ('required_department', models.CharField(blank=True, max_length=20, null=True)),
                ('patient_consent', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_records', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ehr_records', to='ehr.patient')),
            ],
        ),
    ]
